# Data Preperations for Local Training
this script is used to combine all btc and eth 15m and 1m candles to train the models. 

If combined the data has something of about 3-4 years of data, not 3 months.

Folder to the crypto data: Dokumente/git-projects/crypto-data

Strategy for this notebook: 
 - get paths right
 - list all csvs in the folder
 - combine them

In [ ]:
path = "../../../crypto-data
with os.scandir(path) as it:
    for entry in it:
        # if not entry.name.startswith('.') and entry.is_file():
        print(entry)

# Kaggle Environment

In [1]:
# import data from septembre of 2022 since it was rather stable during this period
import pandas as pd
import cudf
import os

iskaggle = os.environ.get('KAGGLE_KERNEL_RUN_TYPE', '')

if iskaggle:
    df = cudf.read_csv("/kaggle/input/btcusdt-2023-6-9/df_xg.csv", index_col=0).reset_index(drop=True)
else:
    df = cudf.read_csv("btc-data/df_xg.csv", index_col=0).reset_index(drop=True)

print(df.shape)
df.head(3)

(11701, 133)

,time,day,hour,10MA,10STD,bb_upper_band,bb_lower_band,open_-3,high_-3,low_-3,...,vwap_8,obv_8,change_8,direction_8,y_bb_down,y_bb_up,y_bb,y_bb_down_test,y_bb_up_test,y_bb_test
0,2023-06-01 02:45:00,1,2,27147.65,57.300422,27262.250844,27033.049156,27247.0,27264.3,27181.5,...,0.002586,1.047671e+07,49.9,1.0,False,False,False,False,False,<NA>
1,2023-06-01 03:00:00,1,3,27172.57,66.008435,27304.586869,27040.553131,27199.0,27343.4,27179.3,...,0.002445,-5.849520e+05,-7.9,-1.0,False,False,False,False,False,<NA>
2,2023-06-01 03:15:00,1,3,27191.57,65.019160,27321.608321,27061.531679,27304.1,27325.0,27274.0,...,0.003635,-8.028397e+06,-29.1,-1.0,False,False,False,False,False,<NA>